openapi: 3.0.0
info:
  version: 1.0.0
  title: Money Mates API
servers:
  - url: 'https://example.com/api'

paths:
  /users:
    post:
      tags:
        - users
      summary: create-user-api
      description: This endpoint creates a new user in the system.
      parameters:
        - name: uuid
          in: header
          required: false
          description: uuid provided from auth server
          schema:
            type: string
            format: uuid
            example: "1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p"

      requestBody:
        description: Body to be inserted
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
            examples:
              regular:
                $ref: '#/components/examples/CreateUserRequestExample'

      responses:
        '201':
          description: A user is created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'
              examples:
                regular:
                  $ref: '#/components/examples/CreateUserResponseExample'

    patch:
      tags:
        - users
      summary: update-user-info-api
      description: This endpoint updates a user's email(for now)
      parameters:
        - $ref: '#/components/parameters/UuidHeader'

      requestBody:
        description: Body to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserInfoRequest'
            examples:
              regular:
                $ref: '#/components/examples/UpdateUserInfoRequestExample'
      responses:
        '200':
          description: A user is created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateUserInfoResponse'
              examples:
                regular:
                  $ref: '#/components/examples/UpdateUserInfoResponseExample'

  /groups:
    post:
      tags:
        - groups
      summary: Create new group with users name
      description: |
        ## Dependencies
        - MySQL
          - groups
          - users
          - user_groups

        ## Inner Spec
        ### What will happen when this API is called.
        - Create group with the group name and new record will be inserted into __groups__ table
        - Create user with the users name and new record will be inserted into __users__ table
        - New records will be inserted into __user_group__ table.

      requestBody:
        description: body to set crated.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGroupRequest'
            examples:
              regular:
                $ref: '#/components/examples/CreateGroupRequestBodyExample'
      responses:
        '201':
          description: The group has been created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateGroupResponse'
              examples:
                regular:
                  $ref: '#/components/examples/CreateGroupResponseExample'
        '400':
          description: Invalid request, headers or body
        '401':
          description: Unauthorized
        '500':
          description: DB, dependency or unknown system error.

components:
  parameters:
    UuidHeader:
      name: uuid
      in: header
      required: true
      description: uuid provided from auth server
      schema:
        type: string
        format: uuid
        example: "1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p"

  schemas:
    CreateUserRequest:
      type: object
      required:
        - uuid
        - name
        - email
      properties:
        uuid:
          type: string
          format: uuid
          description: user's uuid generated by auth server(Firebase).
        name:
          type: string
          description: User's name to be created
        email:
          type: string
          format: email
          description: User's email

    CreateUserResponse:
      $ref: '#/components/schemas/UserResponse'

    UpdateUserInfoRequest:
      type: object
      required:
        - old_uuid
        - new_uuid
        - email
      properties:
        old_uuid:
          type: string
          description: User's tmp uuid selected when user join group
        new_uuid:
          type: string
          description: User's valid uuid generated auth server(Firebase).
        email:
          type: string
          format: email
          description: User's email

    UpdateUserInfoResponse:
      $ref: '#/components/schemas/UserResponse'

    CreateGroupRequest:
      type: object
      required:
        - uuid
        - group_name
        - users_name
      properties:
        uuid:
          type: string
          format: uuid
          description: user's uuid who creates this group. muse be already signed in.
        group_name:
          type: string
          description: group name to be created.
        users_name:
          type: array
          items:
            type: string
          description: users name to be added into the group

    CreateGroupResponse:
      type: object
      required:
        - group_info
        - users_info
      properties:
        group_info:
          $ref: '#/components/schemas/GroupResponse'
        users_info:
          type: array
          items:
            $ref: '#/components/schemas/UserResponse'

    UserResponse:
      type: object
      required:
        - uuid
        - name
        - email
        - is_temporary
        - created_at
        - updated_at
      properties:
        uuid:
          type: string
          format: uuid
          description: User's UUID. Human readable.
        name:
          type: string
          description: User's name created
        email:
          type: string
          format: email
          description: User's email created
        is_temporary:
          type: boolean
          description: return true if user has already singed in.
        created_at:
          type: string
          format: date-time
          description: Creation date.
        updated_at:
          type: string
          format: date-time
          description: Update date.

    GroupResponse:
      type: object
      required:
        - uuid
        - name
        - join_token
        - token_expires
        - created_at
        - updated_at
      properties:
        uuid:
          type: string
          format: uuid
          description: uuid of the group.
        name:
          type: string
          description: name of the group.
        join_token:
          type: string
          format: uuid
          description: token to be used when user join to this group.
        token_expires:
          type: string
          format: date-time
          description: date token will be expired.
        created_at:
          type: string
          format: date-time
          description: date when group was created.
        updated_at:
          type: string
          format: date-time
          description: date when group info was updated.

  examples:
    CreateGroupResponseExample:
      value:
        group_info:
          uuid: "123e4567-e89b-12d3-a456-426614174000"
          name: "Fruits"
          joinToken: "76e4a9e0-df3b-11ec-9d64-0242ac120002"
          tokenExpires: "2023-12-31T23:59:59+09:00"
          createdAt: "2023-01-01T00:00:00+09:00"
          updatedAt: "2023-01-02T00:00:00+09:00"
        users_info:
          - uuid: "789e4567-e89b-12d3-a456-426614174000"
            name: "apple"
            email: "apple@example.com"
            is_temporary: false
            createdAt: "2023-01-01T00:00:00+09:00"
            updatedAt: "2023-01-02T00:00:00+09:00"
          - uuid: "456e4567-e89b-12d3-a456-426614174000"
            name: "banana"
            email: ""
            is_temporary: true
            createdAt: "2023-01-01T00:00:00+09:00"
            updatedAt: "2023-01-02T00:00:00+09:00"
          - uuid: "123e4567-e89b-12d3-a456-426614174001"
            name: "grape"
            email: ""
            is_temporary: true
            createdAt: "2023-01-01T00:00:00+09:00"
            updatedAt: "2023-01-02T00:00:00+09:00"

    CreateGroupRequestBodyExample:
      value:
        uuid: "789e4567-e89b-12d3-a456-426614174000"
        group_name: "Fruits"
        users_name:
          - "apple"
          - "banana"
          - "grape"

    CreateUserRequestExample:
      value:
        uuid: "789e4567-e89b-12d3-a456-426614174000"
        user_name: "山田 花子"
        email: "hanako-yamada@gmail.com"

    UpdateUserInfoRequestExample:
      value:
        old_uuid: "789e4567-e89b-12d3-a456-426614174000"
        new_uuid: "789e4567-e89b-12d3-a456-426614174000"
        email: "hanako-yamada@gmail.com"

    CreateUserResponseExample:
      value:
        uuid: "1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p"
        name: "山田 花子"
        email: "hanako-yamada@gmail.com"
        is_temporary: false
        created_at: "2023-04-01T12:00:00+09:00"
        updated_at: "2023-04-01T12:00:00+09:00"

    UpdateUserInfoResponseExample:
      value:
        uuid: "1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p"
        name: "山田 花子"
        email: "hanako-yamada@gmail.com"
        is_temporary: false
        created_at: "2023-04-01T12:00:00+09:00"
        updated_at: "2023-04-01T12:00:00+09:00"
